### ISSUE TITLE
Fatal Error: getVersion() on a non-object

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub-modules-mail#33]
Updated to latest version of Mail and now the modules list is down.

```txt
Modules directory

Fatal error: Call to a member function getVersion() on a non-object in /home/***/***/***/public_shtml/protected/modules_core/admin/libs/OnlineModuleManager.php on line 181
```

It also removed the mail module all together from the HumHub installation. 

The logging has this message over and over

```txt

    error  Thu, 12 Mar 2015 18:37:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185457449 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:36:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185397449 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:35:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185337449 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:34:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185277450 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:33:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185217454 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:32:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185157455 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:32:25 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "admin".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('admin') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/admin/ ---
    error  Thu, 12 Mar 2015 18:31:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185097454 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:30:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426185037508 HTTP_REFERER=http://herbsy.cf/dashboard ---
    error  Thu, 12 Mar 2015 18:29:38 +0000  exception.CHttpException.404
    exception 'CHttpException' with message 'Unable to resolve the request "mail/mail/GetMessageCount".' in /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /home/***/***/***/public_shtml/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') #1 /home/***/***/***/public_shtml/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /home/***/***/***/public_shtml/index.php(45): CApplication->run() #3 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=2d32dacd35c63f0c5de57de21b8682bc83f72402&_=1426184977453 HTTP_REFERER=http://herbsy.cf/dashboard ---

```

With only other error

```txt
Loading of module mail failed! Alias "application.modules.mail.MailModule" is invalid. Make sure it points to an existing PHP file and the file is readable. in /home/***/***/***/public_shtml/protected/components/ModuleManager.php (241) in /home/***/***/***/public_shtml/protected/modules_core/admin/libs/OnlineModuleManager.php (179) in /home/***/***/***/public_shtml/protected/modules_core/admin/views/module/_header.php (5) in /home/***/***/***/public_shtml/protected/components/Controller.php (198) in /home/***/***/***/public_shtml/protected/modules_core/admin/views/module/list.php (5) 
```

However the directory is writable, and chowned correctly.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/67d8e43d2b97d78c725f4665508c959000ae2f28
